Repository cloudfoundry/capi-k8s-release, pull requests merged in 2020-04, with the labels that each got.

#30 Add LICENSE
  LICENSE
Labels: scheduled

#29 Bump builder image to 0.0.94
  templates/cf-autodetect-builder.yml
  values.yml
Labels: unscheduled

#33 Use the internal loggregator URL
  templates/ccng-config.lib.yml
Labels: in progress
